### ISSUE TITLE
Using angular modal service from react 

### ISSUE THREAD

**Issue by corinaivn** [bubblydoo/angular-react#2]
Hi,

I am trying to use a modal service in a react component. But I am unable to use the useObservable hook in this scenario.
The react component is embedded in react-wrapper but that seems to work ok. The problem is that I don't seem to understand how to obtain the result of the modal window display. 
Could you please provide me some guidance on this? 
Thank you!

```ts
export function Confirmation() {
  const flxModalService = useInjected(FlxModalService)
  const [confirmation, setConfirmation] = useState<boolean | null>(null);

  const confirm = () => {
    const modal = flxModalService.show(
      ConfirmationModalComponent,
      {
        closeOnBackdropClick: false,
        backdropClass: 'overlay-backdrop',
      },
      {
        message: `Are you sure you want to continue?`,
        btnOkText: `Ok`,
      }
    )
    const [data, error, completed] = useObservable(modal.data$)
    if (data.confirm) {
      console.log('Confirmed')      
    }
  }

  return (
    <div style={{ border: "1px solid", padding: "5px", margin: "5px" }}>
      <p>this is React: </p>
      <button onClick={ () => confirm()}>Confirm</button>
    </div>
  );
}
```

**Comment by hansottowirtz** [comment]
Hi Corina, your React component is not valid because you can only use a hook in your render function, not in a callback function: https://react.dev/warnings/invalid-hook-call-warning

In this case I'd use [`firstValueFrom`](https://rxjs.dev/api/index/function/firstValueFrom):

```ts
const data = await firstValueFrom(modal.data$)
```

or you can put the modal.data$ in a `useState` and then use `useObservable` from that state.

I will close this issue as there's no bug in this repository, but feel free to ask more questions.
