### ISSUE TITLE
Property `children` shadowed in <react-wrapper>

### ISSUE THREAD

**Issue by sgrtho** [bubblydoo/angular-react#4]
### Issue:

The forwarded `children` property is shadowed by `undefined` in `<react-wrapper>` if provided through the wrapper's input `props`.

### Example:

Leads to _undefined_ children in function components.

`<react-wrapper [component]="SomeComponent" [props]="{ children: 'Text' }"></react-wrapper>`

### Reason:

From [react-wrapper.component.tsx](https://github.com/bubblydoo/angular-react/blob/main/projects/angular-react/src/lib/react-wrapper/react-wrapper.component.tsx), Line 90+:

`
    const children = this.props.children ? undefined : (
      <AngularTemplateOutlet tmpl={this.childrenTmpl} />
    );
`

…and further:

`<this.component {...this.props}>{children}</this.component>`

When _children_ is provided through the tag content, then it will shadow the extra property-provided version. I am unsure if this concerns every version of _React_ or every type of component, but it concerns at least version _18.2_ using functional components.

### Should Fix:

```
let props = this.props;

if(!Object.prototype.hasOwnProperty.call(props, "children")) {
  props = { ...props, children: <AngularTemplateOutlet tmpl={this.childrenTmpl} /> };
} 
```

…and further:

`<this.component {...props} />`

**Comment by hansottowirtz** [comment]
Hi! Thanks for opening this issue, that's a really basic use case I missed. It's fixed in 0.4.5, see [this story](https://angular-react-bubblydoo.vercel.app/?path=/story/tests-button--showcase).

I'd be curious to know more about why you're using this library! If you have any time, please let me know why you're using it and what could be better.
